### ISSUE TITLE
Create `ConstellationCard` component

### ISSUE THREAD

**Issue by kgallego** [NahejL/www.stelo.space#3]
<img width="269" alt="Screen Shot 2019-10-05 at 3 02 46 PM" src="https://user-images.githubusercontent.com/37840194/66259658-8209f980-e781-11e9-92cb-b1e56c7600b3.png">

**Comment by kgallego** [comment]
<img width="269" alt="Screen Shot 2019-10-05 at 3 02 46 PM" src="https://user-images.githubusercontent.com/37840194/66259658-8209f980-e781-11e9-92cb-b1e56c7600b3.png">

**Comment by ANDREYDEN** [comment]
When should we close this issue? When the card is fully implemented?
